# Generated by Django 5.0.6 on 2024-06-10 06:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BikeRackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_geom', models.CharField(max_length=255)),
                ('BoroCode', models.IntegerField()),
                ('BoroName', models.CharField(max_length=50)),
                ('BoroCD', models.IntegerField()),
                ('CounDist', models.IntegerField()),
                ('AssemDist', models.IntegerField()),
                ('StSenDist', models.IntegerField()),
                ('CongDist', models.IntegerField()),
                ('Program', models.CharField(max_length=50)),
                ('Site_ID', models.CharField(max_length=50)),
                ('Group_ID', models.CharField(max_length=50)),
                ('Borough', models.CharField(max_length=50)),
                ('IFOAddress', models.CharField(max_length=100)),
                ('OnStreet', models.CharField(max_length=100)),
                ('FromStreet', models.CharField(max_length=100)),
                ('ToStreet', models.CharField(max_length=100)),
                ('Side_of_St', models.CharField(max_length=1)),
                ('RackType', models.CharField(max_length=50)),
                ('Date_Inst', models.DateField(null=True)),
                ('X', models.FloatField()),
                ('Y', models.FloatField()),
                ('NTAName', models.CharField(max_length=100)),
                ('FEMAFldz', models.CharField(max_length=50)),
                ('FEMAFldT', models.CharField(max_length=50)),
                ('HrcEvac', models.IntegerField(blank=True, null=True)),
                ('Condition', models.CharField(blank=True, max_length=50, null=True)),
                ('Updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('Notes', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('image_id', models.IntegerField(blank=True, null=True)),
                ('assessment_count', models.IntegerField(default=0)),
                ('assessment_streak', models.IntegerField(blank=True, default=0, null=True)),
                ('distance_traveled', models.IntegerField(blank=True, default=0, null=True)),
                ('achievements_completed', models.IntegerField(blank=True, default=0, null=True)),
                ('badges_earned', models.IntegerField(blank=True, default=0, null=True)),
                ('mistery_boxes_earned', models.IntegerField(blank=True, default=0, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('achievements', models.ManyToManyField(blank=True, to='bike_parking_app.achievements')),
                ('badges', models.ManyToManyField(blank=True, to='bike_parking_app.badge')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
