# Generated by Django 5.0.2 on 2024-02-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/none/noImg0.jpg', null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
