# Generated by Django 4.2.2 on 2024-03-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parking_app', '0002_user_image_delete_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeRackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_geom', models.CharField(max_length=50)),
                ('BoroCode', models.IntegerField()),
                ('BoroName', models.CharField(max_length=50)),
                ('BoroCD', models.IntegerField()),
                ('CounDist', models.IntegerField()),
                ('AssemDist', models.IntegerField()),
                ('StSenDist', models.IntegerField()),
                ('CongDist', models.IntegerField()),
                ('Program', models.CharField(max_length=50)),
                ('Site_ID', models.CharField(max_length=50)),
                ('Group_ID', models.CharField(max_length=50)),
                ('Borough', models.CharField(max_length=50)),
                ('IFOAddress', models.CharField(max_length=100)),
                ('OnStreet', models.CharField(max_length=100)),
                ('FromStreet', models.CharField(max_length=100)),
                ('ToStreet', models.CharField(max_length=100)),
                ('Side_of_St', models.CharField(max_length=1)),
                ('RackType', models.CharField(max_length=50)),
                ('Date_Inst', models.DateTimeField()),
                ('X', models.FloatField()),
                ('Y', models.FloatField()),
                ('NTAName', models.CharField(max_length=100)),
                ('FEMAFldz', models.CharField(max_length=50)),
                ('FEMAFldT', models.CharField(max_length=50)),
                ('HrcEvac', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='none/noImg0.jpg', null=True, upload_to=''),
        ),
    ]
