# Generated by Django 4.2.2 on 2024-03-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parking_app', '0003_bikerackdata_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikerackdata',
            name='HrcEvac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikerackdata',
            name='the_geom',
            field=models.CharField(max_length=255),
        ),
    ]
