# Generated by Django 4.2.2 on 2024-03-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parking_app', '0004_alter_bikerackdata_hrcevac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikerackdata',
            name='Date_Inst',
            field=models.CharField(max_length=100),
        ),
    ]
