# Generated by Django 4.2.2 on 2024-03-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parking_app', '0006_alter_bikerackdata_date_inst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikerackdata',
            name='Date_Inst',
            field=models.DateField(null=True),
        ),
    ]
