# Generated by Django 4.2.2 on 2024-03-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parking_app', '0007_alter_bikerackdata_date_inst'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikerackdata',
            name='Condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
