# Generated by Django 4.2.2 on 2024-03-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parking_app', '0008_bikerackdata_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikerackdata',
            name='Updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
