# Generated by Django 4.2.2 on 2024-03-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parking_app', '0009_bikerackdata_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikerackdata',
            name='Notes',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
