# Generated by Django 4.2.2 on 2024-03-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parking_app', '0011_alter_user_image_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default_profile.jpeg', null=True, upload_to=''),
        ),
    ]
