# Generated by Django 4.2.2 on 2024-04-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parking_app', '0015_virtualreward'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achivements',
            new_name='Achievements',
        ),
        migrations.RemoveField(
            model_name='virtualreward',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='profile_pictures/default_profile.jpeg', null=True, upload_to='profile_pictures/'),
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
        migrations.DeleteModel(
            name='VirtualReward',
        ),
    ]
