# Generated by Django 4.2.2 on 2024-04-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parking_app', '0017_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(blank=True, to='bike_parking_app.achievements'),
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
    ]
