# Generated by Django 4.2.2 on 2024-05-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parking_app', '0021_remove_user_image_user_image_id_delete_useravatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievements_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='assessment_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='assessment_streak',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='badges_earned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='distance_traveled',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
