# Generated by Django 4.2.2 on 2024-05-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parking_app', '0022_user_achievements_completed_user_assessment_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mistery_boxes_earned',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
