# Generated by Django 4.2.2 on 2024-05-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parking_app', '0023_user_mistery_boxes_earned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='images',
        ),
        migrations.AlterField(
            model_name='user',
            name='achievements_completed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='assessment_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='assessment_streak',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='badges_earned',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='distance_traveled',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mistery_boxes_earned',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
