# Generated by Django 4.2.2 on 2024-05-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parking_app', '0024_remove_badge_images_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBadge',
        ),
    ]
