# Generated by Django 4.2.2 on 2024-05-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parking_app', '0025_delete_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(blank=True, to='bike_parking_app.badge'),
        ),
    ]
