# Generated by Django 4.2.2 on 2024-05-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parking_app', '0027_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assessment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
    ]
